# Generated by Django 4.2.27 on 2026-01-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='会社名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('tel', models.CharField(max_length=255, verbose_name='電話番号')),
                ('home_page', models.CharField(max_length=255, verbose_name='会社ホームページ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(choices=[(1, '全権限付与'), (2, '閲覧・編集権限'), (3, '閲覧権限')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='ロール名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ロール',
                'verbose_name_plural': 'ロール',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_name', models.CharField(max_length=255, verbose_name='アプリケーション名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='local_mysql_models.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'アプリケーション',
                'verbose_name_plural': 'アプリケーション',
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='姓')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='local_mysql_models.company', verbose_name='会社')),
                ('role', models.ForeignKey(db_column='role_id', default=3, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='local_mysql_models.role', verbose_name='ロール')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'users',
                'indexes': [models.Index(fields=['company'], name='users_company_c76839_idx'), models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['role'], name='users_role_id_7a277c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('manual_id', models.AutoField(primary_key=True, serialize=False)),
                ('manual_name', models.CharField(max_length=200, verbose_name='マニュアル名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('file_extension', models.CharField(max_length=500, verbose_name='ファイル拡張子')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='ファイルサイズ(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='local_mysql_models.application')),
            ],
            options={
                'verbose_name': 'マニュアル',
                'verbose_name_plural': 'マニュアル',
                'db_table': 'manuals',
                'indexes': [models.Index(fields=['application'], name='manuals_applica_45fe3e_idx'), models.Index(fields=['is_deleted'], name='manuals_is_dele_137539_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['company'], name='application_company_8872a4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_name'], name='application_applica_b84e8c_idx'),
        ),
    ]
